version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: startProject_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5431:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
